---
- name: create the 'stack' user
  user:
    name: stack
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash

- name: allow 'stack' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: 'stack ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: set up authorized keys for the stack user
  authorized_key: user=stack key="{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub
...
